# Node, Mongo, Redis, Nginx
# Minh Chu <scsilver94@gmail.com>

version: "2"
services:
  api:
    image: node:boron
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./api:/home/node/api/
    working_dir: /home/node/api
    command: yarn start
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"

  mongodb:
    image: mongo:3.0
    volumes:
      - mongodb:/data/db/
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"

  redis:
    image: redis:3.2-alpine
    networks:
      - backend
    volumes:
      - redis:/data/
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"

  nginx:
    image: nginx:stable-alpine
    depends_on:
      - api
    networks:
      - backend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
      - "443:443"
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"

networks:
  backend:

volumes:
  mongodb:
  redis:
